# -*- coding: utf-8 -*-
"""Drawing_On_Image.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11R48RSKybYEGeExV-sWDe3bjMkAVGi_B
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

blank_img = np.zeros(shape = (512,512,3), dtype = np.uint8)

plt.imshow(blank_img)

cv2.rectangle(blank_img,pt1=(380,10),pt2=(500,150),color= (255,0,0),thickness = 10)
plt.imshow(blank_img)

cv2.rectangle(blank_img,pt1=(200,200), pt2=(300,300),color = (0,0,255),thickness =5)
plt.imshow(blank_img)

cv2.circle(blank_img,center=(250,250),radius = 50,color= (0,255,0),thickness=2)
plt.imshow(blank_img)

cv2.circle(blank_img,center=(100,100),radius = 50,color= (255,0,0),thickness=-1) #thickness =-1 == filled circle
plt.imshow(blank_img)

cv2.line(blank_img,pt1 = (0,0),pt2=(500,500),color = (0,0,255),thickness =5)
plt.imshow(blank_img)

font = cv2.FONT_HERSHEY_SIMPLEX
cv2.putText(blank_img,text='Hello',org=(10,500), fontFace=font,fontScale=4,color=(255,255,255),
        thickness=3,lineType = cv2.LINE_AA)
#org= botton left start of text 
plt.imshow(blank_img)

blank_img2 = np.zeros(shape = (512,512,3), dtype = np.int32)
plt.imshow(blank_img2)

vertices = np.array([[200,400],[100,300],[200,200],[300,200],[400,300],[300,400]],dtype = np.int32)
vertices

vertices.shape # but openCV wants it in 3 dimensions

# casting in 3 dimension
pts = vertices.reshape((-1,1,2))
pts

pts.shape

cv2.polylines(blank_img2,[pts],isClosed=True, color=(0,255,0), thickness =5)
plt.imshow(blank_img2)