# -*- coding: utf-8 -*-
"""03-Numpy-and-Image-Assessment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pGrksLit5i9GfAIDWYfvqShpyuCZK_la

# NumPy and Image Assessment 

**COMPLETE THE TASKS IN BOLD BELOW.**

**TASK: Import NumPy**
"""

import numpy as np

"""**TASK: Create a 5 by 5 array where every number is a 10**"""

np.ones((5,5))*10



"""**TASK: Run the cell below to create an array of random numbers and see if you can figure out how it works.**"""

# This line sets a "seed" so you get the same random numbers we do
np.random.seed(101)
# This line creates an array of random numbers
arr = np.random.randint(low=0,high=100,size=(5,5))
arr

"""**TASK: What are the largest and smalled values in this array?**"""

arr.max()

arr.min()

"""**TASK: Use PIL and matplotlib to read and display the ../DATA/00-puppy.jpg image.**"""

import matplotlib.pyplot as plt
from PIL import Image
pic = Image.open('00-puppy.jpg')
pic

"""**TASK: Convert the image to a NumPy Array**"""

pic_arr = np.asarray(pic)
pic_arr.shape

"""**FINAL TASK: Use slicing to set the RED and GREEN channels of the picture to 0, then use imshow() to show the isolated blue channel**"""

pic_arr[:,:,0] = 0

pic_arr[:,:,1] = 0

plt.imshow(pic_arr)

"""## Great Job!

----
"""