# -*- coding: utf-8 -*-
"""NumPy_arrays.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O1n-6FudjaLm6d78ghXbZkJHj9di_3l_
"""

import numpy as np

my_list  = [1,2,3]

type(my_list)

myarray = np.array(my_list)
myarray

np.arange(0,10,2) # Returns evenly spaced value within a given

np.zeros(shape=(5,5)) # Returns 5 rows 5 columns

np.ones((2,4))

np.random.seed(101) # Allows to create the same random no each time
arr = np.random.randint(0,100,10)
arr

arr2 = np.random.randint(0,100,10)
arr2

arr.max() # Returns max value of an array

arr.argmax() #returns index of the max value

arr.min() # returns min value of array

arr.argmin() # returns max value of array

arr.mean() # returns mean of array

arr.reshape(2,5) # reshaped to 2 rows 5 colums

mat = np.arange(0,100).reshape(10,10)
mat

mat.shape

row= 4
col =6
mat[row, col]

mat[:,:2]

mat[:,:2].reshape(5,4)

mat[:3,:3] = 0
mat

mynewmat = mat.copy()

mynewmat[0:6,:] = 99
mynewmat

